project_id = "cnpvlloooyyxlgayfzth"

[functions.mentor-chat]
verify_jwt = false

[functions.import-users]
verify_jwt = false

[functions.generate-verse-image]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.generate-presentation-pdf]
verify_jwt = false

[functions.send-schedule-notification]
verify_jwt = false

[functions.notify-schedule-response]
verify_jwt = false
